CALCULATORS = {
    # ── Health / Primary ──
    "bmi": {
        "name": "BMI Calculator",
        "type": "primary",
        "category": "health",
        "section": "Body Composition",
        "icon": "⚖️",
        "url": "/health/bmi",
        "description": "Body Mass Index with WHO categories and ideal weight range.",
        "icon_bg": "var(--green-light)",
        "icon_color": "var(--green)",
        "dependencies": [],
        "derivedFrom": [],
        "suggestNext": ["body_fat", "bmr_tdee", "ideal_body_weight", "ffmi"],
        "storageKey": "bmi",
    },
    "body_fat": {
        "name": "Body Fat %",
        "type": "primary",
        "category": "health",
        "section": "Body Composition",
        "icon": "📏",
        "url": "/health/body-fat",
        "description": "US Navy method — estimate body fat from body measurements.",
        "icon_bg": "var(--purple-light)",
        "icon_color": "var(--purple)",
        "dependencies": [],
        "derivedFrom": [],
        "suggestNext": ["ffmi", "lean_body_mass", "bmi"],
        "storageKey": "bodyFat",
    },
    "bmr_tdee": {
        "name": "BMR & TDEE",
        "type": "primary",
        "category": "health",
        "section": "Body Composition",
        "icon": "🔥",
        "url": "/health/bmr-tdee",
        "description": "Basal metabolic rate, daily calorie needs, and macro targets.",
        "icon_bg": "var(--orange-light)",
        "icon_color": "var(--orange)",
        "dependencies": [],
        "derivedFrom": [],
        "suggestNext": ["protein_intake", "water_intake"],
        "storageKey": "bmrTdee",
    },
    "water_intake": {
        "name": "Water Intake",
        "type": "primary",
        "category": "health",
        "section": "Body Composition",
        "icon": "💧",
        "url": "/health/water-intake",
        "description": "Daily water requirement based on weight, activity, and climate.",
        "icon_bg": "var(--blue-light)",
        "icon_color": "var(--blue)",
        "dependencies": [],
        "derivedFrom": [],
        "suggestNext": ["bmr_tdee"],
        "storageKey": "waterIntake",
    },
    "ldl": {
        "name": "LDL Cholesterol",
        "type": "primary",
        "category": "health",
        "section": "Heart & Lipids",
        "icon": "🫀",
        "url": "/health/ldl",
        "description": "Friedewald formula — LDL from total cholesterol, HDL, and triglycerides.",
        "icon_bg": "var(--orange-light)",
        "icon_color": "var(--orange)",
        "dependencies": [],
        "derivedFrom": [],
        "suggestNext": ["atherogenic_index"],
        "storageKey": "ldl",
    },
    "atherogenic_index": {
        "name": "Atherogenic Index (AIP)",
        "type": "primary",
        "category": "health",
        "section": "Heart & Lipids",
        "icon": "❤️‍🔥",
        "url": "/health/atherogenic-index",
        "description": "Cardiovascular risk from triglycerides and HDL — predicts plaque buildup.",
        "icon_bg": "var(--red-light)",
        "icon_color": "var(--red)",
        "dependencies": [],
        "derivedFrom": [],
        "suggestNext": ["ldl"],
        "storageKey": "atherogenicIndex",
    },
    "hba1c": {
        "name": "HbA1c ↔ Blood Sugar",
        "type": "primary",
        "category": "health",
        "section": "Diabetes",
        "icon": "🔬",
        "url": "/health/hba1c",
        "description": "Convert between HbA1c and estimated average blood glucose.",
        "icon_bg": "var(--accent-light)",
        "icon_color": "var(--accent)",
        "dependencies": [],
        "derivedFrom": [],
        "suggestNext": ["homa_ir"],
        "storageKey": "hba1c",
    },
    "homa_ir": {
        "name": "HOMA-IR",
        "type": "primary",
        "category": "health",
        "section": "Diabetes",
        "icon": "🩸",
        "url": "/health/homa-ir",
        "description": "Insulin resistance index from fasting glucose and insulin levels.",
        "icon_bg": "var(--purple-light)",
        "icon_color": "var(--purple)",
        "dependencies": [],
        "derivedFrom": [],
        "suggestNext": ["hba1c"],
        "storageKey": "homaIr",
    },
    "egfr": {
        "name": "eGFR",
        "type": "primary",
        "category": "health",
        "section": "Kidney",
        "icon": "🫘",
        "url": "/health/egfr",
        "description": "Kidney function — estimated GFR from serum creatinine (CKD-EPI 2021).",
        "icon_bg": "var(--red-light)",
        "icon_color": "var(--red)",
        "dependencies": [],
        "derivedFrom": [],
        "suggestNext": ["corrected_calcium"],
        "storageKey": "egfr",
    },
    "corrected_calcium": {
        "name": "Corrected Calcium",
        "type": "primary",
        "category": "health",
        "section": "Electrolytes",
        "icon": "🦴",
        "url": "/health/corrected-calcium",
        "description": "Adjust total calcium for albumin levels — important when albumin is abnormal.",
        "icon_bg": "#fefce8",
        "icon_color": "#ca8a04",
        "dependencies": [],
        "derivedFrom": [],
        "suggestNext": [],
        "storageKey": "correctedCalcium",
    },
    # ── Health / Derived ──
    "ffmi": {
        "name": "FFMI",
        "type": "derived",
        "category": "health",
        "section": "Body Composition",
        "icon": "💪",
        "url": "/health/ffmi",
        "description": "Fat-Free Mass Index — assess muscle development relative to height.",
        "icon_bg": "var(--green-light)",
        "icon_color": "var(--green)",
        "dependencies": ["body_fat", "bmi"],
        "derivedFrom": ["Body Fat %", "BMI"],
        "suggestNext": ["protein_intake", "lean_body_mass"],
        "storageKey": "ffmi",
    },
    "lean_body_mass": {
        "name": "Lean Body Mass",
        "type": "derived",
        "category": "health",
        "section": "Body Composition",
        "icon": "🏋️",
        "url": "/health/lean-body-mass",
        "description": "Your lean mass and fat mass from body fat percentage and weight.",
        "icon_bg": "var(--blue-light)",
        "icon_color": "var(--blue)",
        "dependencies": ["body_fat"],
        "derivedFrom": ["Body Fat %"],
        "suggestNext": ["ffmi", "protein_intake"],
        "storageKey": "leanBodyMass",
    },
    "protein_intake": {
        "name": "Protein Intake",
        "type": "derived",
        "category": "health",
        "section": "Nutrition",
        "icon": "🥩",
        "url": "/health/protein-intake",
        "description": "Daily protein target based on your weight, goal, and activity level.",
        "icon_bg": "var(--orange-light)",
        "icon_color": "var(--orange)",
        "dependencies": ["bmr_tdee", "body_fat"],
        "derivedFrom": ["BMR & TDEE", "Body Fat %"],
        "suggestNext": ["ffmi"],
        "storageKey": "proteinIntake",
    },
    "ideal_body_weight": {
        "name": "Ideal Body Weight",
        "type": "derived",
        "category": "health",
        "section": "Body Composition",
        "icon": "🎯",
        "url": "/health/ideal-body-weight",
        "description": "Ideal weight range derived from height using Devine, Hamwi & Robinson formulas.",
        "icon_bg": "var(--accent-light)",
        "icon_color": "var(--accent)",
        "dependencies": ["bmi"],
        "derivedFrom": ["BMI"],
        "suggestNext": ["bmr_tdee", "body_fat"],
        "storageKey": "idealBodyWeight",
    },
    # ── Finance / Primary ──
    "sip": {
        "name": "SIP Calculator",
        "type": "primary",
        "category": "finance",
        "section": "Investments",
        "icon": "📈",
        "url": "/finance/sip",
        "description": "See how a fixed monthly SIP compounds over time.",
        "icon_bg": "var(--green-light)",
        "icon_color": "var(--green)",
        "dependencies": [],
        "derivedFrom": [],
        "suggestNext": ["sip_stepup", "retirement_readiness", "inflation_corpus"],
        "storageKey": "sip",
    },
    "sip_stepup": {
        "name": "SIP Step-Up",
        "type": "primary",
        "category": "finance",
        "section": "Investments",
        "icon": "🚀",
        "url": "/finance/sip-stepup",
        "description": "SIP with annual increase — accelerate wealth creation.",
        "icon_bg": "var(--orange-light)",
        "icon_color": "var(--orange)",
        "dependencies": [],
        "derivedFrom": [],
        "suggestNext": ["sip_stepup_lumpsum", "retirement_readiness"],
        "storageKey": "sipStepup",
    },
    "sip_stepup_lumpsum": {
        "name": "SIP Step-Up + Lumpsum",
        "type": "primary",
        "category": "finance",
        "section": "Investments",
        "icon": "💰",
        "url": "/finance/sip-stepup-lumpsum",
        "description": "Combine a lumpsum with an annually increasing SIP.",
        "icon_bg": "var(--purple-light)",
        "icon_color": "var(--purple)",
        "dependencies": [],
        "derivedFrom": [],
        "suggestNext": ["inflation_corpus"],
        "storageKey": "sipStepupLumpsum",
    },
    "lumpsum": {
        "name": "Lumpsum Calculator",
        "type": "primary",
        "category": "finance",
        "section": "Investments",
        "icon": "💎",
        "url": "/finance/lumpsum",
        "description": "One-time investment growth with compounding returns.",
        "icon_bg": "var(--blue-light)",
        "icon_color": "var(--blue)",
        "dependencies": [],
        "derivedFrom": [],
        "suggestNext": ["retirement_readiness", "inflation_corpus"],
        "storageKey": "lumpsum",
    },
    "fd": {
        "name": "FD Calculator",
        "type": "primary",
        "category": "finance",
        "section": "Investments",
        "icon": "🏧",
        "url": "/finance/fd",
        "description": "Fixed deposit maturity with quarterly/monthly compounding.",
        "icon_bg": "#fefce8",
        "icon_color": "#ca8a04",
        "dependencies": [],
        "derivedFrom": [],
        "suggestNext": [],
        "storageKey": "fd",
    },
    "ppf": {
        "name": "PPF Calculator",
        "type": "primary",
        "category": "finance",
        "section": "Government Schemes",
        "icon": "🏛️",
        "url": "/finance/ppf",
        "description": "Public Provident Fund — 15 year tax-free government scheme.",
        "icon_bg": "var(--accent-light)",
        "icon_color": "var(--accent)",
        "dependencies": [],
        "derivedFrom": [],
        "suggestNext": [],
        "storageKey": "ppf",
    },
    "emi": {
        "name": "EMI Calculator",
        "type": "primary",
        "category": "finance",
        "section": "Loans",
        "icon": "🏠",
        "url": "/finance/emi",
        "description": "Home loan, car loan, personal loan — calculate your monthly EMI.",
        "icon_bg": "var(--red-light)",
        "icon_color": "var(--red)",
        "dependencies": [],
        "derivedFrom": [],
        "suggestNext": [],
        "storageKey": "emi",
    },
    "pf": {
        "name": "PF Calculator",
        "type": "primary",
        "category": "finance",
        "section": "Employment & Retirement",
        "icon": "🏦",
        "url": "/finance/pf",
        "description": "EPF maturity with employer match, interest, and annual increments.",
        "icon_bg": "var(--accent-light)",
        "icon_color": "var(--accent)",
        "dependencies": [],
        "derivedFrom": [],
        "suggestNext": ["retirement", "retirement_readiness"],
        "storageKey": "pf",
    },
    "gratuity": {
        "name": "Gratuity Calculator",
        "type": "primary",
        "category": "finance",
        "section": "Employment & Retirement",
        "icon": "🏅",
        "url": "/finance/gratuity",
        "description": "Gratuity as per Payment of Gratuity Act with tax exemption.",
        "icon_bg": "#fefce8",
        "icon_color": "#ca8a04",
        "dependencies": [],
        "derivedFrom": [],
        "suggestNext": ["retirement_readiness"],
        "storageKey": "gratuity",
    },
    "retirement": {
        "name": "Retirement Calculator",
        "type": "primary",
        "category": "finance",
        "section": "Employment & Retirement",
        "icon": "🌴",
        "url": "/finance/retirement",
        "description": "How much corpus you need and how much to save monthly.",
        "icon_bg": "var(--green-light)",
        "icon_color": "var(--green)",
        "dependencies": [],
        "derivedFrom": [],
        "suggestNext": ["retirement_readiness"],
        "storageKey": "retirement",
    },
    # ── Finance / Derived ──
    "retirement_readiness": {
        "name": "Retirement Readiness",
        "type": "derived",
        "category": "finance",
        "section": "Employment & Retirement",
        "icon": "✅",
        "url": "/finance/retirement-readiness",
        "description": "Score your retirement readiness from your SIP corpus vs retirement target.",
        "icon_bg": "var(--green-light)",
        "icon_color": "var(--green)",
        "dependencies": ["retirement", "sip"],
        "derivedFrom": ["Retirement Calculator", "SIP Calculator"],
        "suggestNext": ["inflation_corpus"],
        "storageKey": "retirementReadiness",
    },
    "inflation_corpus": {
        "name": "Inflation-adjusted Corpus",
        "type": "derived",
        "category": "finance",
        "section": "Investments",
        "icon": "📉",
        "url": "/finance/inflation-corpus",
        "description": "Real purchasing power of your investment corpus after inflation.",
        "icon_bg": "var(--orange-light)",
        "icon_color": "var(--orange)",
        "dependencies": ["sip", "lumpsum"],
        "derivedFrom": ["SIP Calculator", "Lumpsum Calculator"],
        "suggestNext": ["retirement_readiness"],
        "storageKey": "inflationCorpus",
    },
}


def get_by_category(category, calc_type=None):
    result = {k: v for k, v in CALCULATORS.items() if v["category"] == category}
    if calc_type:
        result = {k: v for k, v in result.items() if v["type"] == calc_type}
    return result


def get_sections(category, calc_type="primary"):
    calcs = get_by_category(category, calc_type)
    sections = {}
    for key, meta in calcs.items():
        sec = meta["section"]
        sections.setdefault(sec, []).append((key, meta))
    return sections
